[robinhood]
username = "" #Put your value in the quotes
password = "" #Put your value in the quotes
mfa_code = "" #Put your value in the quotes

[excel]
fileName = "Stocks.xlsx"

[csv]
fileName = "Stocks.csv"